[[headers]]
  for = "/video.m3u8"
  [headers.values]
    Content-Type = "application/vnd.apple.mpegurl"
    Access-Control-Allow-Origin = "*"

[[headers]]
  for = "/segments/*"
  [headers.values]
    Content-Type = "video/mp2t"
    Access-Control-Allow-Origin = "*"
